Repository tieme-ndo/backend, pull requests merged in 2019-09, with the labels that each got.

#51 Fix empty farmers list 404 bug
  controllers/farmer/getFarmers.js
  tests/farmers.test.js
Labels: Ready for QA

#50 Check pw before changing pw
  .prettierrc
  README.md
  controllers/farmer/getFarmers.js
  controllers/user/login.js
  controllers/user/resetPassword.js
  helpers/error.js
  helpers/joiValidate.js
  middlewares/Validations/user/resetPassword.js
  middlewares/errors/badRequest.js
  middlewares/errors/forbidden.js
  middlewares/errors/notFound.js
  middlewares/errors/resourceConflict.js
  middlewares/errors/unauthorized.js
  tests/testsSetup.js
  tests/users.test.js
Labels: Ready for QA

#49 Refactor test suite
  .travis.yml
  README.md
  package.json
  tests/changeRequest.test.js
  tests/farmerInput.js
  tests/farmers.test.js
  tests/helpers.test.js
  tests/home.test.js
  tests/testsSetup.js
  tests/users.test.js
Labels: Ready for review

#54 Update - prevent double entries
  controllers/changeRequest/approveChangeRequest.js
  controllers/changeRequest/getChangeRequests.js
  controllers/farmer/updateFarmer.js
  helpers/convertToDotNotationObject.js
  tests/changeRequest.test.js
  tests/farmers.test.js
  tests/home.test.js
  tests/testsSetup.js
  tests/users.test.js
Labels: Ready for QA

#53 Bugfixes - This branch is used for out of scope small bugfixes, refactors etc.
  .coveralls.yml
  controllers/changeRequest/approveChangeRequest.js
  controllers/changeRequest/getChangeRequests.js
  controllers/changeRequest/index.js
  controllers/farmer/addFarmer.js
  controllers/farmer/getFarmers.js
  controllers/farmer/index.js
  controllers/farmer/statistics.js
  controllers/farmer/updateFarmer.js
  controllers/user/login.js
  controllers/user/register.js
  controllers/user/resetPassword.js
  helpers/calculateAge.js
  helpers/convertToDotNotationObject.js
  helpers/error.js
  helpers/generateToken.js
  helpers/joiValidate.js
  index.js
  middlewares/Validations/farmer/changeRequest.js
  middlewares/Validations/farmer/createFarmer.js
  middlewares/Validations/farmer/validateId.js
  middlewares/Validations/user/createUser.js
  middlewares/errors/badRequest.js
  middlewares/errors/forbidden.js
  middlewares/errors/genericError.js
  middlewares/errors/index.js
  middlewares/errors/notFound.js
  middlewares/errors/resourceConflict.js
  middlewares/errors/unauthorized.js
  middlewares/isAuthorized.js
  middlewares/verifyToken.js
  models/index.js
  models/user.js
  routes/changeRequestRouter.js
  routes/farmerRouter.js
  routes/userRouter.js
  tests/helpers.test.js
  tests/testsSetup.js
Labels: changes Requested
